[platformio]
default_envs = esp32_eth01
src_dir = main

[env:esp32_eth01]
platform = espressif32@6.13.0
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.flash_size = 2MB
board_upload.flash_size = 2MB
build_flags =
    -Wall
    -Wextra
    -Werror
