#ifndef ROVER_G16_PROTOCOL_VERSION_H
#define ROVER_G16_PROTOCOL_VERSION_H

#include <stdint.h>

enum {
    ROVER_G16_PROTOCOL_MAGIC = 0x4547u,
    ROVER_G16_PROTOCOL_VERSION_MAJOR = 1u,
    ROVER_G16_PROTOCOL_VERSION_MINOR = 1u,
    ROVER_G16_REGISTER_BASE = 320u,
    ROVER_G16_REGISTER_COUNT = 64u,
    ROVER_G16_CRC_INPUT_REGISTER_COUNT = 60u,
    ROVER_G16_CHANNEL_COUNT = 16u,
    ROVER_G16_SBUS_FRAME_SIZE = 25u,
};

enum rover_g16_register_offset {
    ROVER_G16_REG_MAGIC = 0,
    ROVER_G16_REG_VERSION_MAJOR = 1,
    ROVER_G16_REG_VERSION_MINOR = 2,
    ROVER_G16_REG_LENGTH = 3,
    ROVER_G16_REG_BEGIN_SEQUENCE = 4,
    ROVER_G16_REG_SESSION_ID = 6,
    ROVER_G16_REG_HEARTBEAT = 8,
    ROVER_G16_REG_SBUS_FRAME_COUNTER = 10,
    ROVER_G16_REG_MONOTONIC_MS = 12,
    ROVER_G16_REG_FRAME_AGE_MS = 14,
    ROVER_G16_REG_SBUS_FLAGS = 15,
    ROVER_G16_REG_CHANNEL_COUNT = 16,
    ROVER_G16_REG_CHANNEL_VALID_MASK = 17,
    ROVER_G16_REG_CHANNEL_RAW = 18,
    ROVER_G16_REG_FRAME_PERIOD_US = 34,
    ROVER_G16_REG_INVALID_FRAME_COUNT = 36,
    ROVER_G16_REG_FRAME_LOST_COUNT = 38,
    ROVER_G16_REG_FAILSAFE_COUNT = 40,
    ROVER_G16_REG_RESERVED = 42,
    ROVER_G16_REG_CRC32 = 60,
    ROVER_G16_REG_END_SEQUENCE = 62,
};

enum rover_g16_sbus_flag {
    ROVER_G16_SBUS_FLAG_VALID = 1u << 0,
    ROVER_G16_SBUS_FLAG_FRAME_LOST = 1u << 1,
    ROVER_G16_SBUS_FLAG_FAILSAFE = 1u << 2,
    ROVER_G16_SBUS_FLAG_ALIVE = 1u << 3,
    ROVER_G16_SBUS_FLAG_FAULT = 1u << 4,
};

_Static_assert(ROVER_G16_REG_CHANNEL_RAW + ROVER_G16_CHANNEL_COUNT ==
                   ROVER_G16_REG_FRAME_PERIOD_US,
               "channel register range must contain exactly 16 channels");
_Static_assert((unsigned)ROVER_G16_REG_CRC32 ==
                   (unsigned)ROVER_G16_CRC_INPUT_REGISTER_COUNT,
               "CRC must cover registers 320 through 379");
_Static_assert(ROVER_G16_REG_END_SEQUENCE + 2 == ROVER_G16_REGISTER_COUNT,
               "protocol register image must contain exactly 64 registers");

#endif
